### ISSUE TITLE
Move all the courses to separate repositories

### ISSUE THREAD

**Issue by szabgab** [LibreLingo/LibreLingo#1803]
There are a few in `temporarily_inactive_courses/` and there is `courses/basque-from-english/` that would be better in separate repositories.

It might be a good idea to set up a GitHub organization for this (e.g. LibreLingo ) and move all the repositories there.

**Comment by kantord** [comment]
> It might be a good idea to set up a GitHub organization for this (e.g. LibreLingo ) and move all the repositories there.

perhaps. But a lot of people want to host courses outside of GitHub already. 

Probably best to start creating a page in the GUI (as opposed to simply the documentation) for showing the different course repos. Initially this could lead to the web gui of the git repo (wherever it might be hosted) and later we can use it as an entry point for the course editor perhaps. (whenever we get to that point)

**Comment by frostedkitsune** [comment]
Yes, I would also go for a seperate single source of course and GUI, and that would be only possible if we have our own course management system, a gui course editor with yaml template, git based hosting.....enabling ppl to use raw git repo seems kinda messy to me

**Comment by frostedkitsune** [comment]
> It might be a good idea to set up a GitHub organization for this (e.g. LibreLingo ) and move all the repositories there.
Indeed, but doing that would cause some problems as the repo url will be changed and the previous url probably wouldn't be accessiable leaving the contributors  in no where , and developement workflows would be broken for few days, then all the articles available online reffering to repo url would also be broken, I have done this before on gitlab, dunno how github handles this, so these things might happen.

another less catastrophic approach would be creating an org then forking this repo under that org and then we would have to notify the contributors to visit new repo url though showing messages in this repo's readme.

**Comment by kantord** [comment]
> .enabling ppl to use raw git repo seems kinda messy to me.

I wouldn't say it's messy, when it's only technical people  who will use it that way. But we need to be able to abstract it away for people who are not technical. An example of achieving this is https://www.gitbook.com/

**Comment by frostedkitsune** [comment]
> But we need to be able to abstract it away for people who are not technical. 

yes, that's what I want to say, ppl who would create course might not be much technical to handle the unnecessary complications of git and github, neither they should! Can't we create a separate git repo for courses and add it to this repo as a git submodule? That would be nice, no?

**Comment by szabgab** [comment]
There is no need to use submodules. We can maintain a file (we already have one) with the list of languages that need to be processed and their source) and the deployment process can use that.

**Comment by szabgab** [comment]
All the courses are now in separate repos
