### ISSUE TITLE
Cancel practice before getting started while showing the md file

### ISSUE THREAD

**Issue by szabgab** [LibreLingo/LibreLingo#1816]
If a skill has also an md file, then when the user clicks on the skill firs the content of that files is shown with a link/button at the top "Practice _____". The only way to cancel this it to click on the back button. Is that the intention? It seems it would be better if there was a "cancel" button or an "x" that will bring the user back to the main page of the course.

**Comment by kantord** [comment]
So from what I read here, this has actually nothing to do with md files. Rather there should simply be a way to go back whether or not there's an md file.

Perhaps and X or a back arrow on top of the page would work out well?

**Comment by szabgab** [comment]
I think an X would be good.

**Comment by kantord** [comment]
this is already implemented
