### ISSUE TITLE
Links in documentation no longer point to the correct location for courses

### ISSUE THREAD

**Issue by nan0s7** [LibreLingo/LibreLingo#1830]
**Describe the bug**
Since courses are being moved to separate repositories, all old links that exist in the documentation point to a directory in the source code that does not exist anymore. 

P.S. I'm more than happy to go through and fix these; I just wanted to submit an issue first to see if someone was already rewriting some documents or anything like that. I don't want to be a nuisance.

**To Reproduce**
1. Go to a file that has a link to a course that has been moved (e.g., https://github.com/kantord/LibreLingo/blob/main/docs/courses/README.md)
2. Find a link to a course that has been moved to an external repository (e.g., Spanish for English speakers)
3. ...profit?

**Expected behavior**
The link should take you to the current repository and or file specified.

**Desktop**
 - Browser: Waterfox
 - Git browser: Github

Thanks for the awesome project! I look forward to contributing and watching the project grow!

**Comment by szabgab** [comment]
I think #1794 and #1796 are related to this, right?

**Comment by nan0s7** [comment]
> I think #1794 and #1796 are related to this, right?

Oh you've already fixed that one! I didn't see that you had already put through a pull request, my bad. 

I can't remember if I saw any others (just heading off to bed now), but I'll check tomorrow sometime. 

I'm not sure if it would be worth adding the inactive courses to the list since they would save someone potentially starting from scratch?

**Comment by szabgab** [comment]
I'd first move them to separate repos #1803 but it seems @kantord is busy with other things.

**Comment by kantord** [comment]
The issue with moving the other remaining courses to other repos is that they don't really have an owner or maintainer. perhaps we can "freeze" them (create a repo where we put those files, link it in the documentation and say that anyone can pick them up again?)

**Comment by kantord** [comment]
Or else I could move them to separate repos under my name, but I'm not really able to maintain them as I don't have knowledge of those languages (or the time, because any free time I have I should focus on stuff that affect all courses and our top priorities)

**Comment by szabgab** [comment]
I think it would be a good idea to move them to other repos and tell people they can pick them up.

**Comment by nan0s7** [comment]
I think an organisation could be worth it in the long run *if* you wish to maintain some sort of control, quality or otherwise, over the language courses. It does introduce additional steps for yourself or any other organisation member, though.
The alternative would be to just maintain a list of the current active maintainer of a course, and thus the most recent version of it.

**Comment by kantord** [comment]
It would be nice to maintain control over the courses. And certainly there will be some criteria for being part of the official deployment. But I think to actually have capacity to monitor the quality of the course content we'd need an actual real life organization with several full time employees :-)

**Comment by nan0s7** [comment]
> It would be nice to maintain control over the courses. And certainly there will be some criteria for being part of the official deployment. But I think to actually have capacity to monitor the quality of the course content we'd need an actual real life organization with several full time employees :-)

Well if there's any way I can help I'm happy to give it a go!

**Comment by pur80a** [comment]
this issue seems to be resolves as courses are in separate repos and the LibreLingo repo belongs to the LibreLingo organisation
