### ISSUE TITLE
Easy bug reporting: link to the course repo from every page of the course

### ISSUE THREAD

**Issue by szabgab** [LibreLingo/LibreLingo#1841]
There should be more powerful ways to report issues with lessons, but as a start there could be a link to the git repo of the course on each page of the course. A link that would open in a new tab.

Later the link could be also like this:

```
https://github.com/kantord/LibreLingo-ES-from-EN/issues/new?title=&body=Direction: English to Spanish%0APhrase: hat%0AExercise type: input-text%0A%0AThe problem:
```

There can be another link saying "This should have been accepted"
for which the link could look like this: (assuming the user already filled in "sombrero"

```
https://github.com/kantord/LibreLingo-ES-from-EN/issues/new?title=sombrero should be also accepted&body=Direction: English to Spanish%0APhrase: hat%0AExercise type: input-text%0A%0AThe problem:
```

**Comment by kantord** [comment]
what if the course is not hosted on github?

**Comment by szabgab** [comment]
Good question. I guess for now those won't have such links till the people who host elsewhere explain how would it be easy to link to them.

**Comment by szabgab** [comment]
We should probably also encourage the users to offer new sentences (in the source language) that they would like to learn and practice. Then we should make it easy for users to post such request in the git repository of the course.

**Comment by kantord** [comment]
> 

or basically a string template

**Comment by szabgab** [comment]
Duplicate of #1753
