### ISSUE TITLE
is the basque course public

### ISSUE THREAD

**Issue by WatchGamingVideos** [LibreLingo/LibreLingo#1979]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Lamdarer** [comment]
What do you mean by "public"?
You can try out the course here: https://librelingo.app/course/basque-from-english
And AFAIK it is mainly developed here: https://github.com/RGBradley/LibreLingo/tree/main/courses/basque-from-english

**Comment by kantord** [comment]
as far as I know it's not considered 'ready' yet, but it can be accessed as @Lamdarer said.

cc. @RGBradley

**Comment by WatchGamingVideos** [comment]
> as far as I know it's not considered 'ready' yet, but it can be accessed as @Lamdarer said.
> 
> cc. @RGBradley

I tried it, I feel like it is ready to be published

**Comment by WatchGamingVideos** [comment]
> What do you mean by "public"? You can try out the course here: https://librelingo.app/course/basque-from-english And AFAIK it is mainly developed here: https://github.com/RGBradley/LibreLingo/tree/main/courses/basque-from-english

Published

**Comment by kantord** [comment]
Then, we should make a plan how to include it on the home page

**Comment by kantord** [comment]
Also make a list of what other essential features need to be included before it can be public. I would like to leave it ultimately up to @RGBradley to decide this, because he is the author of the course and he has the best knowledge about whether is ready or not.

**Comment by WatchGamingVideos** [comment]
> Then, we should make a plan how to include it on the home page

If you have an index.html file, or something similar, try a <button> element

**Comment by kantord** [comment]
I don't mean it from a technical perspective, I'm thinking about designing a better landing page.

Check out our current landing page: https://librelingo.app/

It's ok, but I'm looking for something way more professional once we release multiple languages. We need a design/drawing on how our homepage/landing page should look.

**Comment by WatchGamingVideos** [comment]
> I don't mean it from a technical perspective, I'm thinking about designing a better landing page.
> 
> Check out our current landing page: https://librelingo.app/
> 
> It's ok, but I'm looking for something way more professional once we release multiple languages. We need a design/drawing on how our homepage/landing page should look.

What file has the webpage, ill add a (temporary) button

**Comment by kantord** [comment]
> > I don't mean it from a technical perspective, I'm thinking about designing a better landing page.
> > Check out our current landing page: https://librelingo.app/
> > It's ok, but I'm looking for something way more professional once we release multiple languages. We need a design/drawing on how our homepage/landing page should look.
> 
> What file has the landing page, ill add a (temporary) button

Let's wait for @RGBradley to confirm what's needed before the basque course can be public. We won't make it public if he does not confirm it

**Comment by RGBradley** [comment]
Regarding the Basque Course, it is currently being reviewed by two Basque speakers, but unfortunately both are busy with other items, like school, so current estimates is it won't be reviewed until mid to late summer. I did make a posting on Duolingo as part of an ongoing commentary on Basque, but so far no response. As errors/alternate translations/typos are pointed out to me or I discover them I have been making updates.
One thing that is really needed is a way for users to give feedback, ie alternate translations that should be accepted, as not possible for me to think of all the different ways that a sentence can be translated into English or back to Basque. 
The issue of audio recordings is also a problem as for now it is either everything or nothing. so can't add audio incrementally. 
thanks for you interest
rgb
