### ISSUE TITLE
Add me to contributor list

### ISSUE THREAD

**Issue by WatchGamingVideos** [LibreLingo/LibreLingo#2006]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kantord** [comment]
what type of contribution would you like to be added to? 

https://allcontributors.org/docs/en/emoji-key

**Comment by WatchGamingVideos** [comment]
> what type of contribution would you like to be added to?
> 
> https://allcontributors.org/docs/en/emoji-key

Code

**Comment by kantord** [comment]
> > what type of contribution would you like to be added to?
> > https://allcontributors.org/docs/en/emoji-key
> 
> Code

for that, you need to push code that also ends up being merge due to it being useful. I looked on the repo but I can't find any commit by your name. In order to be recognized as a contributors who pushes code please:

- push code that can be merged and provides tangible value
- demonstrate that you have done so in the past

**Comment by WatchGamingVideos** [comment]
> > > what type of contribution would you like to be added to?
> > > https://allcontributors.org/docs/en/emoji-key
> > 
> > 
> > Code
> 
> for that, you need to push code that also ends up being merge due to it being useful. I looked on the repo but I can't find any commit by your name. In order to be recognized as a contributors who pushes code please:
> 
> * push code that can be merged and provides tangible value
> * demonstrate that you have done so in the past

Its on @RGBradley repo

**Comment by kantord** [comment]
> > > > what type of contribution would you like to be added to?
> > > > https://allcontributors.org/docs/en/emoji-key
> > > 
> > > 
> > > Code
> > 
> > 
> > for that, you need to push code that also ends up being merge due to it being useful. I looked on the repo but I can't find any commit by your name. In order to be recognized as a contributors who pushes code please:
> > 
> > * push code that can be merged and provides tangible value
> > * demonstrate that you have done so in the past
> 
> Its on @RGBradley repo

https://github.com/RGBradley/LibreLingo/commit/9e920cf014efa3b4db8d014e4adb9c859d21b2d5

that commit does not count as code as it modifies course content, not code. there's currently not a way to recognize course content contributors in this repository using allcontributors bot, because the course content is meant to be hosted in separate repositories.

Instead we should create a system that automatically collects data about course contributors and publishes them on a special page that lists the people who have contributes to each specific course.

**Comment by WatchGamingVideos** [comment]
> > > > > what type of contribution would you like to be added to?
> > > > > https://allcontributors.org/docs/en/emoji-key
> > > > 
> > > > 
> > > > Code
> > > 
> > > 
> > > for that, you need to push code that also ends up being merge due to it being useful. I looked on the repo but I can't find any commit by your name. In order to be recognized as a contributors who pushes code please:
> > > 
> > > * push code that can be merged and provides tangible value
> > > * demonstrate that you have done so in the past
> > 
> > 
> > Its on @RGBradley repo
> 
> [RGBradley@9e920cf](https://github.com/RGBradley/LibreLingo/commit/9e920cf014efa3b4db8d014e4adb9c859d21b2d5)
> 
> that commit does not count as code as it modifies course content, not code. there's currently not a way to recognize course content contributors in this repository using allcontributors bot, because the course content is meant to be hosted in separate repositories.
> 
> Instead we should create a system that automatically collects data about course contributors and publishes them on a special page that lists the people who have contributes to each specific course.

So ill take content

**Comment by kantord** [comment]
> > > > > > what type of contribution would you like to be added to?
> > > > > > https://allcontributors.org/docs/en/emoji-key
> > > > > 
> > > > > 
> > > > > Code
> > > > 
> > > > 
> > > > for that, you need to push code that also ends up being merge due to it being useful. I looked on the repo but I can't find any commit by your name. In order to be recognized as a contributors who pushes code please:
> > > > 
> > > > * push code that can be merged and provides tangible value
> > > > * demonstrate that you have done so in the past
> > > 
> > > 
> > > Its on @RGBradley repo
> > 
> > 
> > [RGBradley@9e920cf](https://github.com/RGBradley/LibreLingo/commit/9e920cf014efa3b4db8d014e4adb9c859d21b2d5)
> > that commit does not count as code as it modifies course content, not code. there's currently not a way to recognize course content contributors in this repository using allcontributors bot, because the course content is meant to be hosted in separate repositories.
> > Instead we should create a system that automatically collects data about course contributors and publishes them on a special page that lists the people who have contributes to each specific course.
> 
> So ill take content

We are not using that to recognize course content contributors anymore. As I said, the courses are now meant to be separate from LibreLingo itself

**Comment by WatchGamingVideos** [comment]
are there any other courses, id like to link them to landing page

**Comment by WatchGamingVideos** [comment]
> > > > > > > what type of contribution would you like to be added to?
> > > > > > > https://allcontributors.org/docs/en/emoji-key
> > > > > > 
> > > > > > 
> > > > > > Code
> > > > > 
> > > > > 
> > > > > for that, you need to push code that also ends up being merge due to it being useful. I looked on the repo but I can't find any commit by your name. In order to be recognized as a contributors who pushes code please:
> > > > > 
> > > > > * push code that can be merged and provides tangible value
> > > > > * demonstrate that you have done so in the past
> > > > 
> > > > 
> > > > Its on @RGBradley repo
> > > 
> > > 
> > > [RGBradley@9e920cf](https://github.com/RGBradley/LibreLingo/commit/9e920cf014efa3b4db8d014e4adb9c859d21b2d5)
> > > that commit does not count as code as it modifies course content, not code. there's currently not a way to recognize course content contributors in this repository using allcontributors bot, because the course content is meant to be hosted in separate repositories.
> > > Instead we should create a system that automatically collects data about course contributors and publishes them on a special page that lists the people who have contributes to each specific course.
> > 
> > 
> > So ill take content
> 
> We are not using that to recognize course content contributors anymore. As I said, the courses are now meant to be separate from LibreLingo itself

You choose for me then
