### ISSUE TITLE
CI: second push gets green (without running) while first one is still running

### ISSUE THREAD

**Issue by szabgab** [LibreLingo/LibreLingo#2037]
I pushed to main that triggered the CI. While it was running I pushed another change to main. The CI immediately indicated a green mark on this second one. Strange. See screenshot.

![second-ci-is-not-running](https://user-images.githubusercontent.com/48833/152653129-58024072-8c5a-4386-91d2-253fbdc91229.png)

**Comment by kantord** [comment]
I am not sure if we can do anything about this. The explanation is that there's a delay in how GitHub detects which tasks need to be run. It is "fixed" after some minutes of waiting. 

I'm not sure if it's an issue on GitHub's architecture or Semaphore itself. Maybe both at the same time. I have observed this behavior with GitHub actions and other stuff installed from the GitHub marketplace. Basically most of them appear with a delay, and until they appear, github shows that all checks have passed :thinking:  but the delay seems more intense with semaphore, when a lot of stuff are pushed quickly.

If you think anything can be done about this, feel free to reopen. But it seems like it\s more of an issue to be raised with GitHub.

**Comment by kantord** [comment]
the only idea I have is maybe somehow adding something that shows the pipeline to be in progress for a couple minutes

**Comment by szabgab** [comment]
It is ok, I just wanted to document this behavior as I was surprised. Thanks for the explanation.
