### ISSUE TITLE
Add "go back" button to course introduction pages

### ISSUE THREAD

**Issue by kantord** [LibreLingo/LibreLingo#2079]
Modify this page: https://github.com/LibreLingo/LibreLingo/blob/eba232b43ab98606a71d9253024ab50ea8a26e5c/apps/web/src/routes/course/%5BcourseName%5D/skill/%5BskillName%5D/introduction.svelte 

so that there's a way to go back to the main page of the same course. There's already a button that starts practicing the skill, so this button will be added in addition to that.

It should be very simple. Just add a button with the link, just like the practice button now. The URL is pretty simple, here's an example of a URL for a course page: https://librelingo.app/course/spanish-from-english

For comparison, here's an example of a URL of an introduction page: https://librelingo.app/course/spanish-from-english/skill/animals/introduction

**Comment by rodrigo-pova** [comment]
Hello @kantord! I'd like to handle this issue as my first contribution to an open source project 🤓.

**Comment by kantord** [comment]
Hi @rodrigo-pova perfect! :rocket: 

let me know if you need any help

**Comment by rodrigo-pova** [comment]
I'm getting this error as I try to push my branch to the remote
<img width="817" alt="Screen Shot 37" src="https://user-images.githubusercontent.com/83843080/162421653-ef9175c9-1fe6-4baa-b708-7bf5f511c812.png">
I cloned the repo, checked out to a new branch, made the changes and tried to push 🤔. Am I doing something wrong?

**Comment by kantord** [comment]
> I'm getting this error as I try to push my branch to the remote <img alt="Screen Shot 37" width="817" src="https://user-images.githubusercontent.com/83843080/162421653-ef9175c9-1fe6-4baa-b708-7bf5f511c812.png"> I cloned the repo, checked out to a new branch, made the changes and tried to push thinking. Am I doing something wrong?

you need to create your own fork of this repo, push the changes in your own fork and then create the pull request. You are able to create a pull request into the original repo by pushing the branch into your fork

**Comment by kantord** [comment]
@rodrigo-pova would you be interested in doing another pull request? If so, please let me know. I'm happy to help you find the best issue to pick.

Another thing you could do is create a follow-up merge request for your contribution. Basically, you could add an end-to-end test using Cypress. To do that, you'd simply have to extend the following cucumber feature file:

https://github.com/LibreLingo/LibreLingo/blob/179046469c3cfd311c1631577d41bebd09196c8e/apps/web/cypress/integration/introductionPage.feature#L1-L18

look at this folder to see more feature files: https://github.com/LibreLingo/LibreLingo/tree/179046469c3cfd311c1631577d41bebd09196c8e/apps/web/cypress/integration

and look at this folder to see how to implement custom steps for your feature file, if it's needed for your test (but it might not be needed): https://github.com/LibreLingo/LibreLingo/tree/179046469c3cfd311c1631577d41bebd09196c8e/apps/web/cypress/integration/common
