### ISSUE TITLE
Can't use unicode character U+0332 in my Oneida Course

### ISSUE THREAD

**Issue by cutthroat78** [LibreLingo/LibreLingo#2119]
In the Oneida langauge, underlining a part of the word means to whisper that part of the word. Typically, on computers the unicode symbol [U+0332](https://unicode-table.com/en/0332/) is used for underlining and I would like to have this character as a special character in my course, however I can't specify it in the course.yaml because it modifies the character before it. (It ends up making "̲", which doesn't work). 
Is there another way to specify the unicode character to be used in the special characters section in the course.yaml using unicode character codes?
If there isn't another way, may I propose LibreLingo can take something like this that can be used in the Special Characters? part of course.yaml?
```
Special characters:
  - "·"
  - U+0332
```

**Comment by kantord** [comment]
Does this work? 

```yaml
Special characters:
  - "·"
  - "\u0332"
```

according to the yaml specification, that's how it should work. (at least that's what I found here: https://stackoverflow.com/questions/35746109/how-to-do-unicode-escaping-in-yaml-multiline-string)

That being said, I'm wondering how this button will be rendered as this is not a conventional character by any means. Perhaps, we will need to find a way to specify a button label that's different than the actual character? I'm imagining something along the lines of:

```yaml
Special characters:
  - "·"
  - value: "\u0332"
    label: "_"
```

or

```yaml
Special characters:
  - "·"
  - value: "\u0332"
    label: "Whisper"
```

or perhaps if there's some character that represents whispering better

**Comment by cutthroat78** [comment]
Thank you, this works!
Here is what it looks like
![image](https://user-images.githubusercontent.com/55604778/160673672-1287f1a0-096a-492d-9275-e6654a994eaf.png)

I think the value and button label idea you have said there may be a good idea, as it looks strange

(I would rather the underline look like an underline (like in your first button label example) as this is just how the language is written)

**Comment by kantord** [comment]
Hi @cutthroat78 if I understand correctly, there isn't anything left to do here right now. If I misunderstood, please re-open the issue and describe what else is needed

**Comment by cutthroat78** [comment]
Sorry, I forgot to close this issue, whoops
