### ISSUE TITLE
LibreLingo logo should lead back to the course home page, not the main landing page

### ISSUE THREAD

**Issue by kantord** [LibreLingo/LibreLingo#2280]
On all pages that are associated with a course, the LibreLingo logo on the top left corner of the page should lead back to the main page of the course, rather than the main landing page. This is because most people are most likely to only study one language, so most likely they will want to go back to that page. Once the landing page is improved, we can add an alternative way to go back to that page.

An example is this page: https://librelingo.app/course/spanish-from-english/skill/animals/introduction
Current behavior: the button leads to https://librelingo.app/
Expected behavior: the button should lead to https://librelingo.app/course/basque-from-english/

This should apply to all pages that are specifically associated with a course. That means, all the pages that are defined in this folder or one of it's subfolders: https://github.com/LibreLingo/LibreLingo/tree/main/apps/web/src/routes/course/%5BcourseName%5D

This can be probably achieved by changing this file: https://github.com/LibreLingo/LibreLingo/blob/de283649c8e8722aea20407682f2c5fa5169704a/apps/web/src/components/NavBar.svelte

**Comment by yulyasystem** [comment]
I'm happy to help with it :)

**Comment by kantord** [comment]
this is fixed by @yulyasystem  in https://github.com/LibreLingo/LibreLingo/pull/2357
