### ISSUE TITLE
I want to add a new course

### ISSUE THREAD

**Issue by vandersdg** [LibreLingo/LibreLingo#2292]
Hello, I just finished a pt-BR course for English speakers but I am not sure how can I add it to your repo. I am still a newbie using git but here it is: [https://github.com/vandersdg/LibreLingo-ptBR-from-EN](url)

**Comment by cutthroat78** [comment]
I have made a [pull request](https://github.com/vandersdg/LibreLingo-ptBR-from-EN/pull/1) on [your repo](https://github.com/vandersdg/LibreLingo-ptBR-from-EN)

In the pull request, I added to your course.yaml a feature that has LibreLingo auto create and put audio into the lessons using Amazon Polly, when it is being deployed to librelingo.app.

For the course to be on librelingo.app, @kantord (or someone else in the LibreLingo GitHub organisation) will make a repo in the LibreLingo GitHub organisation and move over your course to the new repo. You will be able to work on the course in the new repo. Hopes this helps!

**Comment by vandersdg** [comment]
Thank you very much!

**Comment by cutthroat78** [comment]
I have made another pull request on your repo, adding courses-ci and fixing some issues that courses-ci pointed out

**Comment by vandersdg** [comment]
On it!

**Comment by kantord** [comment]
@vandersdg let us know if you need some more help fixing the remaining issues!

**Comment by vandersdg** [comment]
@kantord I just fixed the issues :smile:

**Comment by kantord** [comment]
> @kantord I just fixed the issues smile

nice

**Comment by kantord** [comment]
@vandersdg I forked your repo into the LibreLingo organization in order to have it in the organization. The benefit of this is that it will be easy to find for anyone who is browsing the LibreLingo organization on github searching for courses.

**Comment by kantord** [comment]
I have added a commit to enable this course: https://github.com/LibreLingo/LibreLingo/commit/a66c3cb9435fa19b29827cd6bcf3908375da4931

let's hope that everything will pass for the first try :smile:  I also had to fix some other things because the deployment was already failing for some reason

**Comment by vandersdg** [comment]
Awesome mate! Thanks for your support, I will be contributing as much as I can :)
