### ISSUE TITLE
When 'Phrase' is misspelled (for example 'Phase') a completely useless error message is reported 

### ISSUE THREAD

**Issue by kantord** [LibreLingo/LibreLingo#2437]
Acceptance criteria:

- When such a spelling mistake is introduced, the error message is helpful in
  * Finding out where the error is 
  * Figuring out how to fix it

Note: the error does not have to be so specific and say `You misspelled "Phrase" as "Phaser"` it's enough to say something like `Key "Phrase" not found. Keys found: "Phaser", "Translation"`

And ideally the solution to this would of course also work if it's "Translation" that's misspelled, not "Phaser" :wink: as there's reason to expect that the root of the problem is the same

**Comment by Harsh-Singh-Rajput** [comment]
@kantord can you provide the source where and how to reproduce this error?

**Comment by kantord** [comment]
> @kantord can you provide the source where and how to reproduce this error?

Hi @Harsh-Singh-Rajput, I can't point you to the exact source locatoin

**Comment by kantord** [comment]
> @kantord can you provide the source where and how to reproduce this error?

Hi @Harsh-Singh-Rajput, I cannot point you to the exact source location unfortunately, but it should be relatively easy to figure out after seeing the traceback from the error. You should be able to see the traceback if you reproduce the error.

To reproduce the error, you should

- [Set up your local development env](https://librelingo.app/docs/#setting-up-the-development-environment)
- Introduce this misspelling in [one of the skill YAML files](https://github.com/LibreLingo/LibreLingo/blob/main/courses/test/basics/skills/animals.yaml) in the the course
- Export the course locally using `yarn exportAllCourses`

In order to introduce the misspelling, look at a part of the file like this:

```yaml
Phrases:
  - Phrase: Es un caballo
    Translation: It's a horse
```

and change the spelling of Phrase, for example:

```diff
Phrases:
-  - Phrase: Es un caballo
+  - Phaser: Es un caballo
    Translation: It's a horse
```

**Comment by kantord** [comment]
hi @Harsh-Singh-Rajput I also updated the description with some acceptance criteria in order to clarify the issue

**Comment by Harsh-Singh-Rajput** [comment]
@kantord ohk thanks I will try to solve it.

>

**Comment by kantord** [comment]
How's it going @Harsh-Singh-Rajput ? Need any help here?

**Comment by djgoreli** [comment]
Hi, could I take a look into solving this issue? Thanks!

**Comment by djgoreli** [comment]
Currently, @Abbi-Hackbardt and I have fixed the error with the misspelled Phrase key as specified above. We noticed that you mentioned ensuring that the Translation key also produces good error output when misspelled. However, upon testing it locally, we found that there is already an error in place for when the Translation key is misspelled or missing, which is something like:  'Phrase "Es un caballo" needs to have a "Translation".'

Would it be preferable to leave this error message (that additionally provides which phrase is misspelled) as is, or change it to match the Phrase misspelled error that would be something like: 'Key "Translation" not found. Keys found: "Phrase"'?

**Comment by kantord** [comment]
> Currently, @Abbi-Hackbardt and I have fixed the error with the misspelled Phrase key as specified above. We noticed that you mentioned ensuring that the Translation key also produces good error output when misspelled. However, upon testing it locally, we found that there is already an error in place for when the Translation key is misspelled or missing, which is something like: 'Phrase "Es un caballo" needs to have a "Translation".'
> 
> Would it be preferable to leave this error message (that additionally provides which phrase is misspelled) as is, or change it to match the Phrase misspelled error that would be something like: 'Key "Translation" not found. Keys found: "Phrase"'?

It would be nice to change that one too, however I'm wondering: would it be actually possible to use JSON schema to do this validation :thinking:  In that case maybe a lot of these custom messages could be even removed from the code
