### ISSUE TITLE
Virtual keyboard is cut in half (listening challenge, language with lot of characters)

### ISSUE THREAD

**Issue by kantord** [LibreLingo/LibreLingo#2442]
Reproduce;

- Navigate to https://librelingo.app/course/french-from-english/skill/animals/
- skip to a listening challenge

Screenshot:

![2022-09-25T13:49:17+02:00](https://user-images.githubusercontent.com/3704904/192141950-4fd7cf52-463a-484c-9d40-2239bf4c7b31.png)

**Comment by DanielGall500** [comment]
Hi! I'd like to start working on this project and will take up this issue. :)
