### ISSUE TITLE
Port Python code style checks (black, pylint) to GitHub Actions

### ISSUE THREAD

**Issue by kantord** [LibreLingo/LibreLingo#2466]
[Look at this commit](https://github.com/LibreLingo/LibreLingo/pull/2465/commits/a09e4899f55d7e53b17fb569197fc2f3cf676c45) that ports the `mypy` checks from Semaphore CI to GitHub Actions: https://github.com/LibreLingo/LibreLingo/pull/2465/commits/a09e4899f55d7e53b17fb569197fc2f3cf676c45

This task should be very simple, just repeat the same step for `black` and `pylint`, so that all of those checks are executed using GitHub Actions instead of Semaphore CI.

**Comment by Frey0-0** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by kantord** [comment]
sure @Frey0-0 ! :1st_place_medal:

**Comment by Frey0-0** [comment]
@kantord I have completed this issue and also made a PR. Can you please assign this issue a hacktoberfest label as well?

**Comment by kantord** [comment]
I think it's not necessary to assign such a label to the issues itself, the label is already assigned to the project. If you log in into your hacktoberfest profile, you should be able to see your PR already. Do you see it?

**Comment by Frey0-0** [comment]
oh yes, I do see it thanks @kantord for the information :)
