### ISSUE TITLE
GitHub Actions: run Python checks on OS X

### ISSUE THREAD

**Issue by kantord** [LibreLingo/LibreLingo#2479]
In [a previous pull request](https://github.com/LibreLingo/LibreLingo/pull/2465/commits/cc1d5809d0bcc61d0c12077be00751fefcf6708e), I ported our Python checks to GitHub Actions.

In that pull request, I only made the tests work on Ubuntu, not on OS X or Windows. This is because, while not much should change between the platforms, due to some small differences the pipeline was failing.

**In this task, please make sure that the CI passes with the OSX platform**.

To do that, you can extend the `matrix` property in this file:

https://github.com/LibreLingo/LibreLingo/blob/cc1d5809d0bcc61d0c12077be00751fefcf6708e/.github/workflows/python.yml#L5-L10

You can consult the GitHub Actions documentation to see how to add different operating systems to the matrix: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-adding-configurations

**Now the hard part is, after making this change, you have to make sure that the CI passes, that is, you have to figure out the reason for the failure based on the errors and make changes so that everything passes**. 

If you need more context, you can always check out the [YouTube video](https://www.youtube.com/watch?v=JHjmguNqA1s&t=264s) where I write the code that you are changing now.

**Comment by kantord** [comment]
for some reason I cannot assign you @vil02 :sweat_smile:

**Comment by kantord** [comment]
Maybe it's only possible if you comment on the issue

**Comment by vil02** [comment]
@kantord I think that this issue can be closed because of #2518
