### ISSUE TITLE
Code style: fix 2 instances of lines that are too long

### ISSUE THREAD

**Issue by kantord** [LibreLingo/LibreLingo#2499]
Earlier, pylint was set up to enforces that lines don't get too long. However, automatic formatting does not solve that issue in some cases, so 2 instances where this pylint rule is ignored were introduced. See this code for those 2 examples of `# pylint: disable=line-too-long` while also making sure that the tests no longer fail. So you need to manually edit the lines that create the problem.

https://github.com/LibreLingo/LibreLingo/blob/1da7e69de3bcc18c8a965f1cd480aa5394a94b54/apps/librelingo_yaml_loader/librelingo_yaml_loader/yaml_loader.py#L168-L214

**Comment by rsk2** [comment]
@kantord, can I work on this?

**Comment by kantord** [comment]
of course @rsk2 go for it! :rocket:

**Comment by rsk2** [comment]
Hi @kantord, I have created a pull request for this issue.
