### ISSUE TITLE
version update needed for librelingo-fakes

### ISSUE THREAD

**Issue by MignonBelongie** [LibreLingo/LibreLingo#2753]
Latest published version of librelingo-fakes (3.0.1) is not compatible with latest version of librelingo-types (3.3.0).

In particular, the version of fakes.py currently in https://pypi.org/project/librelingo-fakes/ tries to create Skill objects without a filename argument.

**Comment by kantord** [comment]
Hi @MignonBelongie thanks! I released a new version, can you please let me know if it works for your usecase now? 

Thanks. Closing the issue, please reopen if the problem persists

**Comment by MignonBelongie** [comment]
Thanks! My use case was working through your tutorial. I had gotten around this issue by specifying the local instance of librelingo-fakes, but now it works as described in the tutorial.
