### ISSUE TITLE
Cancel learning session back drop screen

### ISSUE THREAD

**Issue by Bouaziz-aitd** [LibreLingo/LibreLingo#2799]
This is to report an issue encountered when a learning session is canceled. The skill that was running was in the Basics module. Canceling the learning session from the skill brings the user to the attached location while it should have been sent back to the main menu.
![Screen cancel LL session](https://user-images.githubusercontent.com/127974293/229376746-b3a1e008-aaf5-446a-a6f3-f687cea262c6.JPG)

**Comment by kantord** [comment]
Should be fixed now, let's see if it really works :crossed_fingers:  should be deployed in a couple minutes

**Comment by Bouaziz-aitd** [comment]
I just tested this and it works indeed. The program sends the user to the page displayed at the end of a skill proposing to continue to the main course page.
