### ISSUE TITLE
Broken link in Readme

### ISSUE THREAD

**Issue by jraufeisen** [LibreLingo/LibreLingo#3029]
The readme links to [omnilingo.xyz](https://www.omnilingo.xyz), which does not serve any content.
It should probably be replaced, e.g. with a link to [https://github.com/omnilingo/omnilingo](https://github.com/omnilingo/omnilingo)

**Comment by kantord** [comment]
ok, looks like it is an outdated link, would you please be so kind an open a pull request to fix it? :pray:
