### ISSUE TITLE
https://github.com/LibreLingo/LibreLingo#donate refers to defunct GitHub sponsors

### ISSUE THREAD

**Issue by bwildenhain** [LibreLingo/LibreLingo#3101]
Hi,

I recently got the information from Github that @kantord no longer accepts donations via GitHub Sponsors, but https://github.com/LibreLingo/LibreLingo#donate still links to it. If you do not plan to reenable this sponsoring method, it would be a good idea to refer to https://liberapay.com/kantord instead (as a sidenode: liberapay also supports donation via SEPA/IBAN transfer, which is more privacy friendly than Paypal which is currently the only accepted method for https://liberapay.com/kantord). #2420

**Comment by kantord** [comment]
thank you for reporting @bwildenhain !

**Comment by thibaultmol** [comment]
So... no donations? (liberapay account is closed I see)

I don't like the enshitification that Duolingo is experiencing like every other platform of it's kind. And something like LibreLingo could be a shining alternative but probably needs lots more development. Without donations, i'm afraid it won't happen
